site_name: The Reserve at Kings Point Community Association Documents
site_url: https://rakpca.github.io/documents
theme:
  name: material
nav:
  - Home: index.md 
  - Articles of Incorporation: articles-of-incorporation.md
  - By-Laws: by-laws.md
  - Declarations of Covenants, Conditions, and Restrictions: ccrs.md
  - Restrictive Covenants - Section 3: restrictive-covenants-section-3.md
  - Restrictive Covenants - Section 5: restrictive-covenants-section-5.md
  - Restrictive Covenants - Section 6: restrictive-covenants-section-6.md
  - Restrictive Covenants - Section 8: restrictive-covenants-section-8.md
  - Restrictive Covenants - Section 9: restrictive-covenants-section-9.md
  - Notice of Dedicatory Instruments - Guidelines and Policies: notice-dedicatory-instruments-guidelines-policies.md
